CREATE TABLE IF NOT EXISTS email_otps (
    id SERIAL NOT NULL PRIMARY KEY,
    email TEXT NOT NULL,
    otp TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);